language: node_js
node_js:
  - "8"
cache:
  directories:
    - "node_modules"
script:
  # - npm test
  #
services:
  - mysql
test:
  adapter: mysql2
  database: persona
  username: root
  encoding: utf8
before_install:
  - mysql -e 'CREATE DATABASE persona;'

env:
  global:
    - secure: "iX9WlacrSNmqqCOMH1AO9jf5fEGcMX0VczxOHdALVtbDD/V+mhpTK0pIFVgkwftHDy9cIpY4SkvKmVR9P7d6wDObbPK4TSBBgiTLsjSpeZnmmpymqGZxAyBhAiEt84vD/P1sa41Ui1o5LckhtSAGji4fS87GFcdpqCpi5Zu9x+bJcEGyFIG2moTkp5r3NW3VL8AJiuf+3JT1N/kQfp/+lnnIbojlFhZ9Sd1Hl/AakE7aTzXTWGdrdZ8L+MYHn+aVXzb/yzjLx/z4Ca/XWd6Udz/D+NFJuOjXKNblbET/Vs3ZqxWUFpTz0zcM0FoWnG8tMKYjhqmkf4jzlGE41zzekZkMF6NxBw6NAvamw3VBQa8DYCbQjnzRc0GRDB4jVue2Sf7oJSXJkw9j9FbjmF6CG2I99oMKznOWeuwU1JmMHdbvko8w399taZ/n82mcxwqGVAkyeSaapUKbYeSpCgBZe8Oa8LKIn0mF5isF+RsMFClnJSSpfAwyP60VZfQSkzDnbcZvqJLilefZPd2A0uTNC6B9nAc1YDytC69yFhc+2AXrBvGePPS4JkxhQl6ByBqgSjqFuwmzcCkPs4KgtNhe2BXqteLxFHD9BN2ZyIMXDtVQrw4iGShQi3MfTyh882KQZzlBndH0LyDxSie1Z1+ee9f3rjZdJCncCZshH6AMKRg="
    - secure: "F46Mzuu3V9egGdoWUmQVALsNzXi/9BkUrUxSZTrmtD/hBP12Gud82LBiOgS79b/jD79HUOUbFzfkqML93eeXk+X4LvE9SPx82aqYci/SMlnK6qTtqk1ShBtM+SCS5pt4GM4aqaDMOc62ft6Ol7nUtcrQKWWTewmu8NSG4HQFlIBVM5881q5lSkazk2UR75V41/Il6XSSwvDNCH93Clp2j6Uc4+HRrScGtew0N4AyjFM9UwiGqEMZtdY58iRAtX7wp10Qq2KZkHr8phAN77BEj6TEH4iembfKHdIhchFlpjx3TO0BmY76zZ01InEGLm/e8ZDflR3xjx+bxnPZx1ypo8VYoVKbfQlmtef1Sk09NAAmGOcT07fbBnyjbFhNB107KkpETsBj6gB0pIek0wj4ntHQ/b6oidyewvfLk4+SyKSeV77EX/EF98MdVTuNpd4R+WNAnkj2NHEoBFlZ1PC4E7sqxkOYXtVOOmJnOID1ulpc1+KQJDb6XVq0mRAa1XEyuvax+c7yHO9lGYg33Azlr2UQyIzVrq0wcueD7JIKDHJmuZ2Yy88eiyee4A8di07UOCFGrW9YUDkCSxUOFsS9KfIaKCl9MIe2+nzy0axEzhH5LcIfPHDBLYEcLmx8mFnz1aZ+yDg47wCPGWmqPNPOeFK5Fl25YNVVcYtejJ9lpvI="
    - secure: "dllr/6JhqO+YM00rf4swLx/vt0TSGB+9bRcb9BokgtX2usZDSbbbzlgcFH1U7L6RBTpDq1378dka3OTw69OprtQCxBM93e1ykSpIAFeyJsuNzhcyANzAU5bC7XXovhb5e85ovaJ+axO/BlfoIbxPe1EbwzoY2etIOWYxDJMLd82UM3KaO3E9SqZpy9ZKaafqVtv11WaAxeqWbRzl0jFxsEj6EiSiHiN/toPtjsCs2oyGkpnF/TlTHHxnXal8hMeMbdqUwaO1hIGRQk40HRrS9bi2FbUFYohxjMe0jx5r3/gkUecSO0dWXirAoPl4sK6LMwN98OmU6XIjIJZthuE305NqgoSq08Fe0PkB2c4spQ1Z5qHpPawgx5WgwZKryrmdxfboUU41QFiyuAvcYaPMQl31XGMYECVzMUEOwtqXyKPhWwiwiQOxh76eA4v2v5+1zsymaPSXva1E83V+0Vrxx3TYnIg46RfjTl8vsuSugHyfYGod8Xvkp3/J2jvrRv7PRdYsO47o5CccH1Bv/YkbicaLGm4a0A0JKYGJ0RM4+nejnLJvChKIq53+58TB0uoYlaePyD2PLOmWu0UVV/OGAztRbCvmy96SgM30SSqejRBuXMYtaXywXGzkcp/7bzazmUcptvfh806XRCMDGEoNxhqSykRoa6xHc8yeQglFAhw="
    - secure: "NeaBtFVWWO8V+EpfiFpx9y0SGndZyPHzQfGyi3JgzWaoKO05/0TF0DOC/qgOgxcvV8KpuHmRe1ZFouG+IjFUkQqK2w0H/hkd/f+U9tFb9M5FEMyibo4JA5mJdI+x6ZnWdHEbs/xEvtYmOgnyw0tEqtilJkrtkxoEgjHDFmpS5t5sZNjBaDMvQ8pATiwVXQC6/3R2GnSTnmoRQ5sZEQ2i2EviOpO6JjiGRdDf6/5ti3WryebKjOVyadoEKfrvsltplPINAG5Zw9hARm76x433r/fWm2CV+/47VluhlGxj/9vAdNwY9QmeFMX0AryxiSPEIbxQpSdacrJCu2eCS/oHP6xp0W1K2o5wifKel7aG5PSRHluALfzBpx9s0wv+HhhVrLvEfS4nIbxF1z1kRN9f+eFmrInKbbhAmhKZzQmrET+kZHIQm4in6SP119MMQfl0BBN7dHiR5FRm9jgmTQzBIHPofr7KsjdRY8sXm/eaIEaR/GeQla1JSmJ5obzj3FnIdxg4FE6nGlgRWVVFRjnwqnCvEjedTwY4L3suLxNVNlnyR8Q3JE+IuRlvOjcklNjfexitkqCdn5rgolwGhlGEisdO5h2Lkka4U1Crxzexuz6guhpOl33ok9LfQM3fUPh5CEgspowZ2EszmNgshclc6Br4RI/ZMAh2Rjx+BYsAgr4="

